### ISSUE TITLE
Issues Compiling On CentOS-6.7

### ISSUE THREAD

**Issue by nomadlogic** [dspeterson/dory#1]
Hi There,
I am attempting to compile dory on a CentOS-6.7 system following your directions located at doc/centos_6_5_env.md and build_install.md.  I have compiled gcc482-4.8.2-1.el6.x86_64 and have installed our sites python-2.7 RPM's which are in production use.  It looks like I'm having issues with scons though.

```
(dory)[pwright@host-10-10-20-75 dory]$ build --release --import_path dory
scons: Entering directory `/home/pwright/git/dory'
  File "/home/pwright/git/dory/SConstruct", line 135

    prog_libs = {'pthread', 'dl', 'rt'}

                          ^

SyntaxError: invalid syntax
```

I did verify that I am using python2.7 inside my virtualenv environment - but perhaps I'm missing something else?

```
(dory)[pwright@host-10-10-20-75 dory]$ python --version
Python 2.7.6
(dory)[pwright
```

Thanks in advance!

**Comment by dspeterson** [comment]
Hi nomadlogic,

Thanks very much for finding this issue, and creating a bug report.  I just fixed the problem and created a new release containing the fix.  Please give version 1.1.1 a try.  The problem was that the older Python version that comes with CentOS 6 was being used to run scons, rather than the version provided by the virtualenv.  This behavior was due to the scons executable itself being a Python script whose first line is `#! /usr/bin/python`, which forces the older python version to be used.  I fixed the `bash_defs` file in the root of the source tree so the correct python version will be used on CentOS 6.  I didn't notice the problem because typically when I build Dory, I just run the `build_all` script which doesn't suffer from the problem you discovered.  Let me know if you run into any more problems.

Regards,
Dave

**Comment by nomadlogic** [comment]
Thanks for the quick fix Dave!  In retrospect this makes total sense now.

Cheers,
-pete wright
