### ISSUE TITLE
Docker build fails

### ISSUE THREAD

**Issue by swestcott** [dspeterson/dory#4]
Docker build fails with,

```
$ docker build -t swestcott/dory:latest .
<snip>
--2016-09-06 11:59:10--  http://googletest.googlecode.com/files/gtest-1.7.0.zip
Resolving googletest.googlecode.com (googletest.googlecode.com)... 64.233.166.82, 2a00:1450:400c:c09::52
Connecting to googletest.googlecode.com (googletest.googlecode.com)|64.233.166.82|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-09-06 11:59:11 ERROR 404: Not Found.
```

I tried switching to https://github.com/google/googletest/archive/release-1.7.0.zip, but it looks like the build process for gtest has changed also. I hope to look into this further, but if someone else wants to to raise a PR, that'd be grand.

**Comment by dspeterson** [comment]
It looks like the Dockerfile is trying to install google test framework inside the container. This is no longer necessary because Dory's github repo now contains Google test framework, which is built directly from dory's repo. Therefore I believe the fix is as simple as completely removing the Google test framework stuff from the Dockerfile. Please give this a try, and submit a pull request if it fixes the problem.

Thanks,
Dave

**Comment by dspeterson** [comment]
Pull request has been merged. Thanks!
