### ISSUE TITLE
Have to specify --allow_large_unix_datagrams even if --receive_socket_name is not used

### ISSUE THREAD

**Issue by kipras** [dspeterson/dory#9]
Hi,
when i start Dory it complains like this:
```
Starting dory: Error during server initialization: [src/dory/dory_server.cc, 106]; You didn't specify allow_large_unix_datagrams, and max_input_msg_size is large enough that clients sending large datagrams will need to increase SO_SNDBUF above the default value.  Either decrease max_input_msg_size or specify allow_large_unix_datagrams.
```

I don't pass `--max_input_msg_size` so it should be at the default 64k. However i pass messages to dory using a unix stream socket (`--receive_stream_socket_name`) on which the `--allow_large_unix_datagrams` setting has no effect and i don't pass a unix datagram socket (`--receive_socket_name`). Yet it still asks to set  `--allow_large_unix_datagrams`. And after setting that - it now asks to set `--receive_socket_name` :)
```
Starting dory: Error: Option --allow_large_unix_datagrams is only allowed when --receive_socket_name is specified.
```

So now i have to specify an additional datagram socket even though i'm not going to use it, and also set ` --allow_large_unix_datagrams`. Perhaps during the config parameter check Dory should only ask to specify `--allow_large_unix_datagrams` if `--receive_socket_name` is used?

Dory version: 2.0.2 (built from source).

**Comment by dspeterson** [comment]
Hi kipras,

Dory definitely shouldn't be doing its UNIX datagram size test if --receive_socket_name wasn't specified.  This is a bug, and can cause a spurious error message like the one you see.  However, I'm surprised that you see the error even without specifying a value for --max_input_msg_size.  Maybe it's because the net.core.wmem_default sysctl setting that governs the default value for SO_SNDBUF (see /proc/sys/net/core/wmem_default ) is lower on your system than typically found.  While looking at the code, I noticed a second bug: the permission bits on Dory's UNIX stream socket are set according to the --receive_socket_mode argument rather than --receive_stream_socket_mode.  I'm working on a fix for both bugs, and should have it ready shortly.  Hopefully this will fix the behavior you observe.  Thanks very much for your bug report!

Cheers,
Dave

**Comment by dspeterson** [comment]
Ok, both bugs are fixed.  Please give version 2.0.3 a try.

**Comment by kipras** [comment]
Tried 2.0.3 and yep, no need to specify those datagram arguments anymore, thanks. And thank you for the super quick fix! :)
